version: "3.8"

services:
  mono-app-api:
    image: pavlitoh/mono-map:latest
    container_name: mono-app-api
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://root:root@mongo/
      - MAIL_SECRET_KEY=wnryhjktesmjxwvt
      - MAIL_SERVICE=gmail
      - MAIL_USER=hjuan247@gmail.com
      - MAPBOX_TOKEN=pk.eyJ1IjoianVhbmZyOTciLCJhIjoiY2x4cnhqZGZpMWUzdTJrb2Qxd2k5Z3huYSJ9.Kp99lB1snn3xzzi26jKy4w
    ports:
      - "3001:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: